version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=kramjatt@42.fr
      - PGADMIN_DEFAULT_PASSWORD=admin

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: ./data/postgreSQL

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: ../data/postgreSQL

  postgres_data:

networks:
  transcendence:
    name: transcendence
    driver: bridge