version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: kramjatt
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: PMU
    ports:
      - '5432:5432'
    restart: always