version: '3.8'
services:
  backend:
    build:
      context: ./requirements/back
      dockerfile: Dockerfile
    volumes:
      - backenddata:/src/dist
    ports:
      - '8082:8080'
    depends_on:
      - postgres
    restart: always

  frontend:
    build:
      context: ./requirements/front
      dockerfile: Dockerfile
    volumes:
      - frontdata:/app/dist
    ports:
      - '8081:80'
    restart: always

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
      - frontdata:/usr/share/nginx/html
    depends_on:
      - frontend
    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: kramjatt
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: PMU
    ports:
      - '5432:5432'
    restart: always

volumes:
  backenddata:
    name: backenddata
    driver: local
  frontdata:
    name: frontdata
    driver: local