version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    ports:
      - "5433:5432"

  dbeaver:
    build:
      context: .
      dockerfile: requirements/dbeaver/Dockerfile
    command: /bin/bash -c "while :; do sleep 10; done"