server{
  	listen      443 ssl http2 default_server;
  	listen [::]:443 ssl http2 default_server;
    
    ssl_certificate /ft_transcendence.crt;
	ssl_certificate_key /ft_transcendence.key;
	ssl_protocols TLSv1.2 TLSv1.3;

    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;
     
    location / {
        try_files $uri $uri/ /index.html;
    }
}
